plugins {
    id 'java-library'
    id 'jacoco'
    id 'idea'
    id 'signing'
    id 'maven-publish'
}

repositories {
    mavenCentral()
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}

group 'com.iheartradio.m3u8'
version '0.2.7-SNAPSHOT'

base {
    archivesName = 'open-m3u8'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    testRuntimeOnly 'org.slf4j:slf4j-log4j12:1.7.36'
    testRuntimeOnly 'log4j:log4j:1.2.17'
}

task javadocJar(type: Jar) {
    archiveClassifier = 'javadoc'
    from javadoc
}

task sourcesJar(type: Jar) {
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}

artifacts {
    archives javadocJar, sourcesJar
}

signing {
    required { gradle.taskGraph.hasTask("publish") }
    sign publishing.publications.mavenJava
}

jacoco {
    toolVersion = '0.8.12'
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }
}

test {
    finalizedBy jacocoTestReport
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourcesJar
            artifact javadocJar

            pom {
                name = 'Open M3U8'
                packaging = 'jar'
                description = 'An open source M3U8 playlist parser java library.'
                url = 'https://github.com/iheartradio/open-m3u8/'

                scm {
                    connection = 'scm:git:https://github.com/iheartradio/open-m3u8.git/'
                    developerConnection = 'scm:git:https://github.com/iheartradio/open-m3u8.git/'
                    url = 'https://github.com/iheartradio/open-m3u8/'
                }

                licenses {
                    license {
                        name = 'The MIT License'
                        url = 'http://opensource.org/licenses/MIT'
                    }
                }

                developers {
                    developer {
                        id = 'iheartradio-oss'
                        name = 'Daniel Tashjian'
                        email = 'danieltashjian@iheartmedia.com'
                    }
                }
            }
        }
    }

    repositories {
        maven {
            def releasesRepoUrl = "https://oss.sonatype.org/service/local/staging/deploy/maven2/"
            def snapshotsRepoUrl = "https://oss.sonatype.org/content/repositories/snapshots/"
            url = version.toString().endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl

            credentials {
                username = findProperty('ossrhUsername') ?: ''
                password = findProperty('ossrhPassword') ?: ''
            }
        }
    }
}
